name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '09 17 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue does not seem to be taken up. Might be closed if not major'
        stale-pr-message: 'PR has gone stale. Please finish working on it soon'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 30
